version: "3.8"
services:
  viniplay:
    image: ardovini/viniplay:latest
    container_name: viniplay
    ports:
      - "8998:8998"
    restart: unless-stopped
    volumes:
      - ./viniplay-data:/data
    env_file:
      - ./.env
